### ISSUE TITLE
The dataset homographies are imprecise

### ISSUE THREAD

**Issue by angelcarro** [vislab-tecnico-lisboa/hda_code#12]
Hi!

I think the homographies released in v1.3 of the dataset are quite imprecise.
I did not found calibration information of the cameras and the images have lens distortion. Is there any calibration information available?
Have the homographies been obtained directly with the provided uncalibrated images?

Thanks!

**Comment by WurmD** [comment]
That is the case.
No further calibration is available besides what's provided here and with the dataset proper

**Comment by angelcarro** [comment]
OK. I am going to modify the homographies to fix some incorrect positions.
Also, the approximate position of each camera in the map is provided in the dataset in a matlab figure. However, the height of each camera is not provided, which would be useful for my research. Are these heights known? Could you provide an approximate value?
Thanks again.

**Comment by WurmD** [comment]
Hi, we found the code used to compute the homographies: https://www.dropbox.com/sh/votkw5nt0ibo4tq/AADWGQnheJQN1BD2Pd-6aFPSa?dl=0

It does not require the height of the cameras, only the points in the map (which are known have all height 0), and the same points clicked in each camera image

**Comment by angelcarro** [comment]
Thanks!
