### ISSUE TITLE
invalid header

### ISSUE THREAD

**Issue by s2pr** [vislab-tecnico-lisboa/hda_code#13]
hi, I want get all  images from .seq file.
    I use seqIo() function to decode, and i get 4516 images from camera02.seq，but others  .seq  get none, 
    I running seqIo() , get wrong message: 'invalid header'.
    Is I do something wrong, or these .seq are  wrong.

**Comment by WurmD** [comment]
Use this to get the images instead: https://github.com/vislab-tecnico-lisboa/hda_code/issues/7
