### ISSUE TITLE
HDA Annotations .txt

### ISSUE THREAD

**Issue by amitbcp** [vislab-tecnico-lisboa/hda_code#9]
Hi,

While my team was working on understanding the dataset, can you please help us understand the format of the TXT file in the  HDA annotations folder ?

The fields occ , loc have binary fields but I am having hard time understand the significance wrt to images and there values. Also the hide flag for every person?

It would be very helpful if you can throw some light on it as the hda_detections doesn't have person id to  research on MOT usecase with the project

**Comment by WurmD** [comment]
Hi ami

I don't understand your question. Each track has indeed an associated person id.

If you still need help post a snippet of annotation txt that is confusing you

**Comment by amitbcp** [comment]
Hi @WurmD  

For example, in hda_annotations for camera53.txt L5-L10
-----------------------------------
lbl='person032' str=39 end=41 hide=0
pos =[815.464029 410.461686 405.179856 390.038314; 128.325219 319.895648 413.364583 480.604352; 0.500000 744.046591 33.541076 56.453409; ]
posv=[0.000000 0.000000 0.000000 0.000000; 0.000000 0.000000 0.000000 0.000000; 0.000000 0.000000 0.000000 0.000000; ]

occl=[1 1 1 ]
lock=[0 0 1 ]

Here, I understand that the str end refers to the start and end frame id for the person. I am confused about hide ,occl & loc fields
I believe that occl means occlusion, but i check the images, the person seemed to be visible. Also I am not sure about lock field ?

Also the confusing part is hda_detections. For the same camera53, the file hda_detections/GtAnnotationsAll/camera53/Detections/allD.txt Line 1-3 is 

53,38,815.46,410.46,405.18,390.04,1
53,39,128.33,319.9,413.36,480.6,1
53,40,0.5,744.05,33.541,56.453,1

the format mentioned is ``` <camera id> <frame> <x><y><w><h><detections score>```

The person id is not available. I am trying to work with MOT systems and was looking to convert this to something like : 
```<camera id> <frame> <person id>  <x><y><w><h><detections score>```


53,38,person032,815.46,410.46,405.18,390.04,1


So could you please help me with this : 
1. In case there is already a version which has person annotation with detections ?
2. How to read/decipher camera53.txt to create such a file/annotation format

**Comment by amitbcp** [comment]
@WurmD  if you get some time can you please help me with this ?

**Comment by WurmD** [comment]
Hi hi

So, HDA allows the testing/benchmarking of pedestrian detectors, and of people re-indentificators, separately.

Pedestrian detectors receive an image and output bounding boxes
People re-indentificators receive a cropped image and output a person id

I believe hda_detections/ only has pedestrian detections

--

occl really means occluded, and if even a tiny bit of the person was not visible, then it was marked occl 1

lock not relevant to the annotations, it is used by the MATLAB software that uses these text files

hide, I don't even remember, so I believe it is not relevant to the annotations, and only used by the MATLAB software

That clears all the confusing parts correct?

**Comment by amitbcp** [comment]
Thanks @WurmD 
Yes that clears all the confusing part. 
If possible can you share the name of the annotation tool used ? I am working with Python and would be reformatting the text files to create a different annotation set. So may be I can check the annotation tool if it's public

**Comment by WurmD** [comment]
It's Dollár's vbbLabeler included in this repository. It's really badly documented tho :/

**Comment by amitbcp** [comment]
Thanks @WurmD
